<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork1005-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>


<h3> Get to Know a Numpy Array </h3>


You will use the numpy array <code>A</code> for the following questions.


In [1]:
import numpy as np
A=np.array([[11,12],[21,22],[31,32]])


1) Find the type of `x` using the function `type()`.


In [2]:
type(A)

numpy.ndarray

<details><summary>Click here for the solution</summary>

```python
type(A)
```

</details>


2) Find the shape of the array:


In [3]:
A.shape

(3, 2)

<details><summary>Click here for the solution</summary>

```python
A.shape
```

</details>


3) Find the type of data in the array:


In [4]:
A.dtype

dtype('int32')

<details><summary>Click here for the solution</summary>

```python
A.dtype
```

</details>


4) Find the second row of the numpy array <code>A</code>:


In [5]:
A[1]

array([21, 22])

<details><summary>Click here for the solution</summary>

```python
A[1]
```

</details>


<h3>Two Types of Multiplication</h3>


You will use the following numpy arrays for the next questions: 


In [7]:
A=np.array([[11,12],[21,22]])
B=np.array([[1, 0],[0,1]])

1) Multiply array <code>A</code> and <code>B</code>.


In [8]:
C = A * B
C

array([[11,  0],
       [ 0, 22]])

<details><summary>Click here for the solution</summary>

```python
C = A * B
C
```

</details>


2)  Perform matrix multiplication on array <code>A</code> and <code>B</code> (order will not matter in this case).


In [9]:
Z = np.dot(A,B)
Z

array([[11, 12],
       [21, 22]])

<details><summary>Click here for the solution</summary>

```python
Z = np.dot(A,B)
Z
```

</details>


<hr>

<h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
